<script setup>
import data from "../data.json";
</script>

<template>
	<p class="mt-5 mx-16 text-center text-xl">
		Sonic the Hedgehog has awesome music!
	</p>
	<p class="mx-16 text-center text-xl">
		Happy, epic and emotional... This is a test, can you decide which one is the best?
	</p>

	<RouterLink to="/vs"
		class="self-center px-14 py-2 text-2xl bg-red-600 rounded-lg shadow-lg shadow-blue-950 hover:bg-red-500">
		Start
	</RouterLink>

	<div class="albums-cont grow bg-white mt-5 py-12">
		<ul class="albums-slide">
			<li v-for="album in data.albums" :key="`album-${album}`">
				<img class="min-w-48 h-48 rounded-xl shadow-lg shadow-blue-950"
					:src="`./src/assets/imgs/albums/${album}.webp`" :alt="`sonic ${album} album`">
			</li>
		</ul>
		<ul class="albums-slide">
			<li v-for="album in data.albums" :key="`album-repeat-${album}`">
				<img class="min-w-48 h-48 rounded-xl shadow-lg shadow-blue-950"
					:src="`./src/assets/imgs/albums/${album}.webp`" :alt="`sonic ${album} album`">
			</li>
		</ul>
	</div>
</template>

<style scoped>
/* this styles are the key for slide functionality */
.albums-cont{
	display: flex; /* set the two slides in the same row */
	white-space: nowrap; /* make the slide cross out of the window */
	overflow: hidden; /* hide the scroll generated by the white-space:nowrap */
}

.albums-slide {
	display: flex; /* set every li in the same row */
	animation: 50s slide infinite linear; /* linear: set the movement of the animation to the same speed (constant) */
}

.albums-slide img{
	margin: 0 16px;
	/* the separation between every image has to be with margin to avoid more complex style properties that generate the same result */
}

@keyframes slide{
	from{
		transform: translateX(0)
	}
	to{
		transform: translateX(-100%)
	}
	/* 
	there are two slides with the same images. 
	When the first slide move -100% to the left, the second slide will be in the start position as the first slide 
	and then it starts to move. Visually it seems as a single slide repeating itself. 
	*/
}
</style>